"""MINDTRACE domain layer.

Layer 0 of the architecture (``docs/architecture/01-repository-structure.md``):
the shared vocabulary and the canonical schema model. Depends only on the
standard library and pydantic. It must never import ``fastapi``, ``sqlalchemy``,
an LLM provider SDK, or any higher ``mindtrace`` layer -- enforced by
``backend/.importlinter`` and ``tests/unit/test_import_isolation.py``.
"""

from __future__ import annotations

from mindtrace.domain.confidence import (
    CalibrationLedger,
    CalibrationRecord,
    ConfidenceInputs,
    ConfidenceResult,
    EnsembleObservation,
    ExtractionSignal,
)
from mindtrace.domain.consent import ConsentRecord
from mindtrace.domain.decision import (
    Contribution,
    DecisionResult,
    DispositionInputs,
    FactorReading,
    FactorVector,
    WeightVector,
)
from mindtrace.domain.decision_record import Decision, DecisionOption
from mindtrace.domain.enums import (
    BeliefType,
    ChoiceOption,
    ConsentScope,
    DecisionCategory,
    DecisionOutcome,
    DecisionStatus,
    EpistemicState,
    EvidenceSourceKind,
    ExtractionFailureType,
    ExtractionMode,
    FactorDirection,
    FactorTier,
    InterviewItemRole,
    InterviewItemType,
    MemoryType,
    Polarity,
    PosteriorKind,
    ProvenanceSource,
    ScaleLevel,
    SelfReportReliability,
    UncertainReason,
    UserStatus,
)
from mindtrace.domain.errors import (
    DomainError,
    MindtraceError,
    SchemaConsistencyError,
    SchemaError,
    SchemaStructureError,
    SchemaValidationError,
)
from mindtrace.domain.evidence import Evidence
from mindtrace.domain.factors import (
    FactorSpec,
    FactorTaxonomy,
    OrdinalScale,
    load_factor_taxonomy,
    parse_factor_taxonomy,
)
from mindtrace.domain.ids import (
    ConsentRecordId,
    DecisionId,
    DispositionId,
    EventId,
    EvidenceId,
    EvidenceTag,
    FactorId,
    InterviewItemId,
    MemoryId,
    UserId,
)
from mindtrace.domain.interview import (
    DispositionItem,
    InterviewBank,
    InterviewConfig,
    PairwiseItem,
    load_interview_bank,
    parse_interview_bank,
)
from mindtrace.domain.memory import Memory
from mindtrace.domain.provenance import classify_epistemic_state
from mindtrace.domain.refresh_token import RefreshToken
from mindtrace.domain.schema_bundle import SchemaBundle, load_schema_bundle
from mindtrace.domain.traits import (
    BetaPrior,
    CredibleInterval,
    DispositionObservation,
    DispositionPosterior,
    DispositionSpec,
    EffectiveWeightVector,
    ImportanceWeightSpec,
    NormalPrior,
    PairwiseObservation,
    PreferencePosterior,
    ReportConfig,
    TraitModel,
    TraitReport,
    WeightPosterior,
    load_trait_model,
    parse_trait_model,
)
from mindtrace.domain.user import User

__all__ = [
    "BeliefType",
    "BetaPrior",
    "CalibrationLedger",
    "CalibrationRecord",
    "ChoiceOption",
    "ConfidenceInputs",
    "ConfidenceResult",
    "ConsentRecord",
    "ConsentRecordId",
    "ConsentScope",
    "Contribution",
    "CredibleInterval",
    "Decision",
    "DecisionCategory",
    "DecisionId",
    "DecisionOption",
    "DecisionOutcome",
    "DecisionResult",
    "DecisionStatus",
    "DispositionId",
    "DispositionInputs",
    "DispositionItem",
    "DispositionObservation",
    "DispositionPosterior",
    "DispositionSpec",
    "DomainError",
    "EffectiveWeightVector",
    "EnsembleObservation",
    "EpistemicState",
    "EventId",
    "Evidence",
    "EvidenceId",
    "EvidenceSourceKind",
    "EvidenceTag",
    "ExtractionFailureType",
    "ExtractionMode",
    "ExtractionSignal",
    "FactorDirection",
    "FactorId",
    "FactorReading",
    "FactorSpec",
    "FactorTaxonomy",
    "FactorTier",
    "FactorVector",
    "ImportanceWeightSpec",
    "InterviewBank",
    "InterviewConfig",
    "InterviewItemId",
    "InterviewItemRole",
    "InterviewItemType",
    "Memory",
    "MemoryId",
    "MemoryType",
    "MindtraceError",
    "NormalPrior",
    "OrdinalScale",
    "PairwiseItem",
    "PairwiseObservation",
    "Polarity",
    "PosteriorKind",
    "PreferencePosterior",
    "ProvenanceSource",
    "RefreshToken",
    "ReportConfig",
    "ScaleLevel",
    "SchemaBundle",
    "SchemaConsistencyError",
    "SchemaError",
    "SchemaStructureError",
    "SchemaValidationError",
    "SelfReportReliability",
    "TraitModel",
    "TraitReport",
    "UncertainReason",
    "User",
    "UserId",
    "UserStatus",
    "WeightPosterior",
    "WeightVector",
    "classify_epistemic_state",
    "load_factor_taxonomy",
    "load_interview_bank",
    "load_schema_bundle",
    "load_trait_model",
    "parse_factor_taxonomy",
    "parse_interview_bank",
    "parse_trait_model",
]
